### PR TITLE
Adding primrose version command

### PR DESCRIPTION
**Pull request by weightwatchers-carlanderson**
1) adding `primrose version`:

```
root@68cab68e7294:/# primrose version
1.0.6
```

2) fixing missing `data/` so that test suite runs in Docker

### CODE REVIEW

**Comment by weightwatchers-carlanderson** [comment]
Note: `python-dateutil==2.8.0` is changed because of version conflict:

```
ERROR: botocore 1.13.14 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
```

**Comment by weightwatchers-carlanderson** [comment]
@kzecchini I saw that this was approved but any downstream impacts expected of the requirements change?

**Comment by briangrahamww** [comment]
> @kzecchini I saw that this was approved but any downstream impacts expected of the requirements change?

It looks like the only risk would be breaking the s3 writer via `boto3`.  We have tests for it, but would they catch errors in `boto3` when s3 is mocked in the tests?  If we are unsure, does someone have a DAG with s3 writing that they can run to test quickly?

**Comment by kzecchini** [comment]
@weightwatchers-carlanderson @briangrahamww sorry I missed that comment - this requirements change should be fine. 

This is actually fixing an issue in dependencies for boto. If it wasn't broken before then it should still be fine with the proper version. 

I would be more concerned with other dependencies that might use ` python-dateutil>=2.8.1`... Although if there are no errors being thrown for incorrect dependencies then we should be good!

**Comment by briangrahamww** [comment]
> @weightwatchers-carlanderson @briangrahamww sorry I missed that comment - this requirements change should be fine.
> 
> This is actually fixing an issue in dependencies for boto. If it wasn't broken before then it should still be fine with the proper version.
> 
> I would be more concerned with other dependencies that might use ` python-dateutil>=2.8.1`... Although if there are no errors being thrown for incorrect dependencies then we should be good!

👍 I'm going to merge then.

**Pull request merged**
