### PR TITLE
default changelog output for automated github_changelog_generator

### PR DESCRIPTION
**Pull request by kzecchini**
This is the default changelog output from the tool: https://github.com/github-changelog-generator/github-changelog-generator

It is configurable (by github labels, issues/prs, etc.): https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples

Just a draft for now to discuss the format of this automated changelog. I am not sure if we should even use an auto changelog or if we should have this entered manually as part of a PR contribution. 

If auto changelog makes sense, I will add this generation into travis to auto update each release (or periodically on merge to master).

### CODE REVIEW

**Comment by kzecchini** [comment]
fixes #45

**Comment by parul-l** [comment]
I'm a fan of the feature but can you remind me of the downsides?

**Comment by kzecchini** [comment]
@parul-l The downsides are potentially including extraneous information in the changelog or missing key changes if the automated process misses anything that is not tagged properly. We would have to spend some extra care to make sure our github documentation/labeling is correct and up to date. Additionally if the descriptions in PRs/comments are not very well constructed it can cause confusion.

Obviously entering manually there are downsides as well - some are similar to automated. We might miss changes, write unclear changes, document unclearly, etc. But at least for the manual changelog the developer has a change to write the change and others have a chance to review on PR. Instead of it being auto generated during a build process.

The more I think about it the more I like manual edits. Maybe we can start with this auto generated changelog and make changes manually afterwords? We can have a checklist item to edit the changelog on PR contribution.

**Comment by parul-l** [comment]
@kzecchini Thanks for the info. Despite the negatives, I think it's a good way to go. I think we just have to be diligent in tagging/labeling properly. I believe that is somewhat easier than manually developing the changelog. In terms of confusing PR descriptions, I believe we can [change PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) descriptions/comments before merging. Maybe that can be something to add to the checklist when we're about to merge a PR. Not sure if that is bad practice though.

**Comment by briangrahamww** [comment]
I really like the additions. I think PRs titles are descriptive enough. That, plus squashing/making meaningful commit messages should keep the full changelog readable.  As long as we check the checklist in the PR templates. I think the autogenerated solution should work fine

**Comment by briangrahamww** [comment]
Oh wait this is just a sample of the output, it doesn't include the code that auto-generates the changelog

**Comment by kzecchini** [comment]
Closing this PR as it is just the output example - need to implement the auto changelog on release.

**Pull request closed without merging**
